### ISSUE TITLE
Project activity?

### ISSUE THREAD

**Issue by josemanimala** [cloudius-systems/capstan#172]
Hello Folks, 
Just curious as to the status of the project. 

- Is it maintained?
- Are you looking for maintainers?

**Comment by nyh** [comment]
This project was more-or-less subsumed by its fork https://github.com/mikelangelo-project/capstan although now that the Mikelangelo Project (a EU funded research project) has concluded, maybe it's a good idea to the changes back to the "cloudius-systems" project because I'm not sure who has the permissions to the mikelangelo-project one.
Can you please raise this topic on the osv-dev mailing lists on googlegroups, instead of on the bug tracker here, and hopefully @penberg and @miha-plesko @gberginc who have been previous contributors to this project can voice their opinion.
I think the short answer is, yes - the Capstan project is in need of a new maintainer.

**Comment by devurandom** [comment]
Is it correct that the post to the [osv-dev mailing list](https://groups.google.com/forum/#!forum/osv-dev) never happened? If there was one, could you please post a link?
